### ISSUE TITLE
Error with the demo.cli

### ISSUE THREAD

**Issue by Cxiada** [showlab/videollm-online#60]
Hi, when I was running:
python -m demo.cli --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus --attn_implementation sdpa

I got a CUDA error. I tried to set up different Python environments on A100/A800/4090d to run code, but the same error occurred in different versions of PyTorch.:
我遇到了 CUDA索引错误。我尝试在 A100/A800/4090d 上采用不同Python 环境来运行代码，也尝试了不同PyTorch的版本，都出现了同样的错误：
(videollm_online) lenovo@lenovo-ThinkStation-P3-Tower:/mnt/data1/chenxd/videollm-online$ python -m demo.cli --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
[2025-04-24 02:07:16,632] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 163.06it/s]
/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py:2047: UserWarning: for base_model.model.connector.modules_to_save.default.0.weight: copyi             ng from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to thei             r corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py:2047: UserWarning: for base_model.model.connector.modules_to_save.default.0.bias: copying              from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their              corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py:2047: UserWarning: for base_model.model.connector.modules_to_save.default.2.weight: copyi             ng from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to thei             r corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py:2047: UserWarning: for base_model.model.connector.modules_to_save.default.2.bias: copying              from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their              corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
!!! Set vision encoder in the model, only recommended for on in-the-wild inference. Please dont call this for efficient training & evaluation. Instead, do visual feature pre-extraction.
demo/assets/cache/demo/assets/cooking_2fps_384.mp4 -> torch.Size([215, 3, 384, 384]), 2 FPS
  0%|                                                                                                                                                                                 | 0/215]             ../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [64,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [65,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [66,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [67,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [68,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [69,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [70,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [71,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [72,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [73,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [74,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [75,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [76,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [77,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [78,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [79,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [80,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [81,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [82,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [83,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [84,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [85,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [86,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [87,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [88,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [89,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [90,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [91,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [92,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [300,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/data1/chenxd/videollm-online/demo/cli.py", line 54, in <module>
    main(liveinfer)
  File "/mnt/data1/chenxd/videollm-online/demo/cli.py", line 34, in main
    liveinfer.input_video_stream(i / liveinfer.frame_fps)
  File "/mnt/data1/chenxd/videollm-online/demo/inference.py", line 105, in input_video_stream
    frames_embeds = self.model.visual_embed(self.video_tensor[ranger]).split(self.frame_num_tokens)
  File "/mnt/data1/chenxd/videollm-online/models/modeling_live.py", line 24, in visual_embed
    frames = self.vision_encode(self.vision_encoder, frames)
  File "/mnt/data1/chenxd/videollm-online/models/vision_live.py", line 14, in _siglip_vision_encode
    vision_outputs = vision_model(frames)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/transformers/utils/generic.py", line 965, in wrapper
    output = func(self, *args, **kwargs)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/transformers/models/siglip/modeling_siglip.py", line 933, in forward
    hidden_states = self.embeddings(pixel_values, interpolate_pos_encoding=interpolate_pos_encoding)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/transformers/models/siglip/modeling_siglip.py", line 313, in forward
    embeddings = embeddings + self.position_embedding(self.position_ids)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/home/lenovo/miniforge3/envs/videollm_online/lib/python3.10/site-packages/torch/nn/functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by lyl121** [comment]
Hi Cxiada,
Did you manage to solve this issue? I'm facing the same problem.If you found a fix, could you share it? Thanks!

**Comment by lyl121** [comment]
@zhangsmallshark @Cxiada @chenjoya 
Hi 
Did you manage to solve this issue? I'm facing the same problem.If you found a fix, could you share it? Thanks!

**Comment by MaskedYvette** [comment]
me too.how can i fix it?

**Comment by MaskedYvette** [comment]
@Cxiada @lyl121 @chenjoya 
have you fixed this issue?i meet the same isuue

**Comment by chenjoya** [comment]
Solved. The problem should be the empty init in connector. So I made some fix and now it works well, with the latest transformers and pytorch.

<img width="2988" height="1240" alt="Image" src="https://github.com/user-attachments/assets/8656dc6b-ac05-40e0-889c-ec27340a0622" />
